In [1]:
# lstm model
import numpy as np
import pandas as pd
from numpy import array
from numpy import mean
from numpy import std
from numpy import dstack
import scipy.io as sio
from pandas import read_csv
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import to_categorical
from matplotlib import pyplot
import os

Using TensorFlow backend.


In [2]:
# load all movements

skelList = list()
exerciseList = list()

for i in range(1,2):
    
    path, dirs, files = next(os.walk("data/person%i" %i))
    file_count = len(files)
    
    for j in range(1,file_count):
        
        mat = sio.loadmat('data/person%i/myfile%s.mat' %(i,str(j)))
        skelSeq = mat['skelSeq']
        skelSeq = np.around(skelSeq, decimals = 4)
        exerciseNum = mat['exerciseNum']
        skelList.append(skelSeq)
        exerciseList.append(exerciseNum[0].item(0))
#         exerciseList.append(for i in range(skelSeq.shape[1] * skelSeq.shape[2])
#         a = list()
#         a = np.repeat(exerciseNum[0].item(0), skelSeq.shape[1] * skelSeq.shape[2])
#         b = a.tolist()
#         exerciseList.append(b)

        for k in range(0,skelSeq.shape[1] * skelSeq.shape[2]):
            exerciseList.append(exerciseNum[0].item(0))

        

C:\Users\Mahya\Anaconda3\lib\site-packages\scipy\io\matlab\mio.py:208: MatReadWarning: Duplicate variable name "None" in stream - replacing previous with new
Consider mio5.varmats_from_mat to split file into single variable files
  matfile_dict = MR.get_variables(variable_names)


In [3]:
exerciseList = np.array(exerciseList)
print(exerciseList.shape)

(64682,)


In [4]:
print(len(skelList))
print(len(skelList))
skelList[0][0:3,1,0]

57
57


array([-0.0176,  0.0609,  0.1716])

In [5]:
arr = np.zeros((len(exerciseList),3))

print(arr[0,:])
k = 0;
for p in range(0,len(skelList)):
    for i in range(0,25):
        for j in range(0,skelList[p].shape[1]):
            arr[k,:] = skelList[p][0:3,j,i]
            k = k+1
print(arr.shape)

[0. 0. 0.]
(64682, 3)


In [6]:
# load the dataset, returns train and test X and y elements# 
X_train, X_test, y_train, y_test = train_test_split(arr, exerciseList, test_size=0.33, random_state=42)

In [7]:
print(y_train.shape)
print(y_test.shape)

(43336,)
(21346,)


In [8]:
xx_train = np.zeros((X_train.shape[0],1200,3))

for i in range(0,X_train.shape[0]-1200):
    xx_train[i,:,:] = X_train[0+i:1200+i,:]
    
xx_train.shape

(43336, 1200, 3)

In [9]:
print(X_test.shape)
xx_test = np.zeros((X_test.shape[0],1200,3))

for i in range(0,X_test.shape[0]-1200):
    xx_test[i,:,:] = X_test[0+i:1200+i,:]
    
y_train

(21346, 3)


array([ 3, 13,  6, ...,  1,  3, 13])

In [10]:
# x_test_reshaped = np.reshape(X_test,(nb_samples,X_test.shape[0],X_test.shape[1]))

In [11]:
# # fit and evaluate a model
n_timesteps,num_features = 1200, 3

model = Sequential()
model.add(LSTM(100, input_shape=(n_timesteps,num_features)))
model.add(Dropout(0.5))
model.add(Dense(100, activation='relu'))
model.add(Dense(14, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# # fit network
print("fiittt")
model.fit(xx_train, y_train, epochs=200, batch_size=2000, verbose= 0)
# # # evaluate model
print("evaluate")
_, accuracy = model.evaluate(xx_test, y_test, batch_size=2000, verbose=0)

fiittt



KeyboardInterrupt: 

In [ ]:
print("accuracy",accuracy)